# Use an official Node.js runtime as a parent image.
FROM node:20-alpine

# Set the working directory in the container.
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available) to the container.
# This allows Docker to cache the npm install step if dependencies haven't changed.
COPY package*.json ./

# Install dependencies.
RUN npm install

# Copy the rest of the application source code to the container.
COPY . .

# Expose the port on which the Node.js application will run.
EXPOSE 4000

# Define the command to run the application.
CMD [ "npm", "start" ]
